title: Katrin Glöwing
logo: /0221302b6d43d026af99a668acc7e63ab0634f17dbf4e1e205bb570d6525d207.0.jpg
description: Master student in Technical Consulting & Management studies (M. Sc. in 2023) | Working in human resources
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
